// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectFIN.models;

#nullable disable

namespace ProjectFIN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715134412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectFIN.models.Coordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AllowedRadius")
                        .HasColumnType("float");

                    b.Property<double?>("HomeZoneLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("HomeZoneLongitude")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("VehicleVin")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VehicleVin")
                        .IsUnique();

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("ProjectFIN.models.Vehicle", b =>
                {
                    b.Property<string>("Vin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<int>("Engine")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Vin");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator<string>("VehicleType").HasValue("Vehicle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjectFIN.models.ElectricCar", b =>
                {
                    b.HasBaseType("ProjectFIN.models.Vehicle");

                    b.Property<double>("BatteryCapacity")
                        .HasColumnType("float");

                    b.Property<double>("CurrentCharge")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("EV");
                });

            modelBuilder.Entity("ProjectFIN.models.GasolineCar", b =>
                {
                    b.HasBaseType("ProjectFIN.models.Vehicle");

                    b.Property<double>("CurrentFuel")
                        .HasColumnType("float");

                    b.Property<double>("FuelTankCapacity")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Gas");
                });

            modelBuilder.Entity("ProjectFIN.models.Coordinate", b =>
                {
                    b.HasOne("ProjectFIN.models.Vehicle", "Vehicle")
                        .WithOne("LocationData")
                        .HasForeignKey("ProjectFIN.models.Coordinate", "VehicleVin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ProjectFIN.models.Vehicle", b =>
                {
                    b.Navigation("LocationData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
